events { 
    worker_connections 1024; 
}

http {
    # Configurações de timeout para não cair o Node-RED/Grafana
    proxy_read_timeout 900;
    proxy_connect_timeout 900;
    proxy_send_timeout 900;

    server {
        listen 80;
        server_name localhost;

        # 1. NODE-RED
        location /node-red/ {
            proxy_pass http://node-red:1880/;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. GRAFANA
        location / {
            proxy_pass http://grafana:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. INFLUXDB (Opcional se quiser acessar via Web)
        location /influx/ {
            proxy_pass http://influxdb:8086/;
            proxy_set_header Host $host;
        }


        location /api/v2/ {
            proxy_pass http://influxdb:8086/api/v2/;
        }
        location /static/ {
            proxy_pass http://influxdb:8086/static/;
        }
    }
}
